[package]
name = "gtp-control"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.5"
rand = "0.8.5"